<?php
/**
 * @license GPL, or GNU General Public License, version 3
 * @license http://opensource.org/licenses/GPL-3.0
 * @see README.md how to contribute to this project
 */

/**
 * Implements hook_libraries_info().
 */
function uh_mece_libraries_info() {
  $libraries = array();
  $libraries['mece_php'] = array(
    'name' => 'MECE PHP Library',
    'vendor url' => 'https://github.com/UniversityofHelsinki/mece-php',
    'download url' => 'https://github.com/UniversityofHelsinki/mece-php/archive/master.zip',
    'path' => 'src/UniversityofHelsinki/MECE',
    'version callback' => 'uh_mece_library_version_callback',
    'files' => array(
      'php' => array(
        'MultilingualStringValue.php',
        'Message.php',
        'Notification.php',
      ),
    ),
  );

  return $libraries;
}

/**
 * Callback for bypassing version of MECE PHP Client as it does not provide any
 * information or technique to detect it.
 */
function uh_mece_library_version_callback() {
  return TRUE;
}
